### ISSUE TITLE
Explain the analysis the initial paper does

### ISSUE THREAD

**Issue by LucyWilcox** [LucyWilcox/ParticipatoryGreedyRouting#6]

**Comment by LucyWilcox** [comment]
I think we might not need this now that we have been told to demote it. I imagine it would disrupt the flow of the paper. Perhaps we could put more into the annotated bib though and reference it in the paper. 

@KaitlynKeil Thoughts?

**Comment by KaitlynKeil** [comment]
I think what we have now makes sense.
